/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ClassManagers.*;

/**
 *
 * @author Marco Munguia <@markomannder>
 */
public class MainJForm extends javax.swing.JFrame {

    Managers analyzerManager = new Managers();
    DataManager dataManager = new DataManager();

    /**
     * Creates new form MainJForm
     */
    public MainJForm() {
        initComponents();
        this.setTitle("ManderIDE - 1.0");
        analyzerManager.initializeAnalyzer(compileButton, textWriterArea, tokenLogArea, errorLogArea);
        dataManager.dataManager(openFileButton, textWriterArea);
        dataManager.Export(exportError, errorLogArea);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tokenLogArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textWriterArea = new javax.swing.JTextArea();
        cleanButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        errorLogArea = new javax.swing.JTextArea();
        exportTokens = new javax.swing.JButton();
        exportError = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        textWriterArea1 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        textWriterArea2 = new javax.swing.JTextArea();
        openFileButton = new javax.swing.JButton();
        saveFileButton = new javax.swing.JButton();
        saveFileAsButton = new javax.swing.JButton();
        newFileButton = new javax.swing.JButton();
        copyTextButton = new javax.swing.JButton();
        pasteTextButton = new javax.swing.JButton();
        redoButton = new javax.swing.JButton();
        undoButton = new javax.swing.JButton();
        compileButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tokenLogArea.setColumns(20);
        tokenLogArea.setRows(5);
        jScrollPane1.setViewportView(tokenLogArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 120, 324, 680));

        textWriterArea.setColumns(20);
        textWriterArea.setRows(5);
        jScrollPane2.setViewportView(textWriterArea);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 113, 951, 561));

        cleanButton.setText("Limpiar");
        cleanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cleanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 870, 103, -1));

        errorLogArea.setColumns(20);
        errorLogArea.setRows(5);
        jScrollPane5.setViewportView(errorLogArea);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 790, 1010, 190));

        exportTokens.setText("Exportar Tokens");
        exportTokens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportTokensActionPerformed(evt);
            }
        });
        jPanel1.add(exportTokens, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 820, -1, -1));

        exportError.setText("Exportar Errores");
        exportError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportErrorActionPerformed(evt);
            }
        });
        jPanel1.add(exportError, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 820, -1, -1));

        errorLabel.setText("ErrorLog");
        jPanel1.add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 730, 176, 63));

        textWriterArea1.setColumns(20);
        textWriterArea1.setRows(5);
        jScrollPane6.setViewportView(textWriterArea1);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 113, 53, 555));

        textWriterArea2.setColumns(20);
        textWriterArea2.setRows(5);
        jScrollPane7.setViewportView(textWriterArea2);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 680, 951, 52));

        openFileButton.setText("Open File");
        jPanel1.add(openFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 137, 77));

        saveFileButton.setText("Save File");
        jPanel1.add(saveFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 86, 77));

        saveFileAsButton.setText("Save File As");
        jPanel1.add(saveFileAsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, 77));

        newFileButton.setText("New File");
        jPanel1.add(newFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, 77));

        copyTextButton.setText("Copy Text");
        copyTextButton.setToolTipText("");
        jPanel1.add(copyTextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, 77));

        pasteTextButton.setText("Paste Text");
        jPanel1.add(pasteTextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, 77));

        redoButton.setText("Redo");
        jPanel1.add(redoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 74, 77));

        undoButton.setText("Undo");
        jPanel1.add(undoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 76, 77));

        compileButton.setText("Compile");
        jPanel1.add(compileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, 77));

        aboutButton.setText("About Us");
        jPanel1.add(aboutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, 120, 77));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1423, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cleanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cleanButtonActionPerformed

    private void exportTokensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportTokensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportTokensActionPerformed

    private void exportErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportErrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportErrorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton;
    private javax.swing.JButton cleanButton;
    private javax.swing.JButton compileButton;
    private javax.swing.JButton copyTextButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JTextArea errorLogArea;
    private javax.swing.JButton exportError;
    private javax.swing.JButton exportTokens;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton newFileButton;
    private javax.swing.JButton openFileButton;
    private javax.swing.JButton pasteTextButton;
    private javax.swing.JButton redoButton;
    private javax.swing.JButton saveFileAsButton;
    private javax.swing.JButton saveFileButton;
    private javax.swing.JTextArea textWriterArea;
    private javax.swing.JTextArea textWriterArea1;
    private javax.swing.JTextArea textWriterArea2;
    private javax.swing.JTextArea tokenLogArea;
    private javax.swing.JButton undoButton;
    // End of variables declaration//GEN-END:variables
}
