/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import ClassManagers.*;

/**
 *
 * @author Marco Munguia <@markomannder>
 */
public class MainJForm extends javax.swing.JFrame {

    Managers analyzerManager = new Managers();
    DataManager dataManager = new DataManager();
    ButtonManagers buttonManagers = new ButtonManagers();

    /**
     * Creates new form MainJForm
     */
    public MainJForm() {
        initComponents();
        this.setTitle("ManderIDE - 1.0");
        setLocationRelativeTo(null);
        analyzerManager.initializeAnalyzer(compileButton, textWriterArea, tokenLogArea, errorLogArea);
        dataManager.dataManager(openFileButton, textWriterArea);
        dataManager.Export(exportError, errorLogArea);
        buttonManagers.initializeTextAreaButtons(textWriterArea, undoButton, redoButton, copyTextButton, pasteTextButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tokenLogArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textWriterArea = new javax.swing.JTextArea();
        cleanButton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        errorLogArea = new javax.swing.JTextArea();
        exportTokens = new javax.swing.JButton();
        exportError = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        textWriterArea1 = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        textWriterArea2 = new javax.swing.JTextArea();
        openFileButton = new javax.swing.JButton();
        saveFileButton = new javax.swing.JButton();
        saveFileAsButton = new javax.swing.JButton();
        newFileButton = new javax.swing.JButton();
        copyTextButton = new javax.swing.JButton();
        pasteTextButton = new javax.swing.JButton();
        redoButton = new javax.swing.JButton();
        undoButton = new javax.swing.JButton();
        compileButton = new javax.swing.JButton();
        aboutButton = new javax.swing.JButton();
        errorLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tokenLogArea.setBackground(new java.awt.Color(102, 102, 102));
        tokenLogArea.setColumns(20);
        tokenLogArea.setForeground(new java.awt.Color(255, 255, 255));
        tokenLogArea.setRows(5);
        jScrollPane1.setViewportView(tokenLogArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 120, 324, 680));

        textWriterArea.setBackground(new java.awt.Color(102, 102, 102));
        textWriterArea.setColumns(20);
        textWriterArea.setForeground(new java.awt.Color(255, 255, 255));
        textWriterArea.setRows(5);
        jScrollPane2.setViewportView(textWriterArea);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 113, 951, 561));

        cleanButton.setForeground(new java.awt.Color(255, 255, 255));
        cleanButton.setText("Limpiar");
        cleanButton.setBorder(null);
        cleanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanButtonActionPerformed(evt);
            }
        });
        jPanel1.add(cleanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 870, 103, -1));

        errorLogArea.setBackground(new java.awt.Color(102, 102, 102));
        errorLogArea.setColumns(20);
        errorLogArea.setForeground(new java.awt.Color(255, 255, 255));
        errorLogArea.setRows(5);
        jScrollPane5.setViewportView(errorLogArea);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 790, 1010, 190));

        exportTokens.setForeground(new java.awt.Color(255, 255, 255));
        exportTokens.setText("Exportar Tokens");
        exportTokens.setBorder(null);
        exportTokens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportTokensActionPerformed(evt);
            }
        });
        jPanel1.add(exportTokens, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 820, -1, -1));

        exportError.setForeground(new java.awt.Color(255, 255, 255));
        exportError.setText("Exportar Errores");
        exportError.setBorder(null);
        exportError.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportErrorActionPerformed(evt);
            }
        });
        jPanel1.add(exportError, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 820, -1, -1));

        errorLabel.setText("Token Log");
        jPanel1.add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 50, 176, 63));

        textWriterArea1.setBackground(new java.awt.Color(102, 102, 102));
        textWriterArea1.setColumns(20);
        textWriterArea1.setForeground(new java.awt.Color(255, 255, 255));
        textWriterArea1.setRows(5);
        jScrollPane6.setViewportView(textWriterArea1);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 113, 53, 555));

        textWriterArea2.setBackground(new java.awt.Color(102, 102, 102));
        textWriterArea2.setColumns(20);
        textWriterArea2.setForeground(new java.awt.Color(255, 255, 255));
        textWriterArea2.setRows(5);
        jScrollPane7.setViewportView(textWriterArea2);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 680, 951, 52));

        openFileButton.setBackground(new java.awt.Color(0,0,0,0));
        openFileButton.setForeground(new java.awt.Color(255, 255, 255));
        openFileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IDEImages/openFileImage.png"))); // NOI18N
        openFileButton.setText("Open File");
        openFileButton.setBorder(null);
        openFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(openFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 100, 77));

        saveFileButton.setBackground(new java.awt.Color(0,0,0,0));
        saveFileButton.setForeground(new java.awt.Color(255, 255, 255));
        saveFileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IDEImages/saveFileImage.png"))); // NOI18N
        saveFileButton.setText("Save File");
        saveFileButton.setBorder(null);
        saveFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(saveFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 100, 77));

        saveFileAsButton.setBackground(new java.awt.Color(0,0,0,0));
        saveFileAsButton.setForeground(new java.awt.Color(255, 255, 255));
        saveFileAsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IDEImages/saveAsFileImage.png"))); // NOI18N
        saveFileAsButton.setText("Save File As");
        saveFileAsButton.setBorder(null);
        saveFileAsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(saveFileAsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 100, 77));

        newFileButton.setBackground(new java.awt.Color(0,0,0,0));
        newFileButton.setForeground(new java.awt.Color(255, 255, 255));
        newFileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IDEImages/newFileImage.png"))); // NOI18N
        newFileButton.setText("New File");
        newFileButton.setBorder(null);
        newFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(newFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 90, 77));

        copyTextButton.setBackground(new java.awt.Color(0,0,0,0));
        copyTextButton.setForeground(new java.awt.Color(255, 255, 255));
        copyTextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IDEImages/copyTextImage.png"))); // NOI18N
        copyTextButton.setText("Copy Text");
        copyTextButton.setToolTipText("");
        copyTextButton.setAutoscrolls(true);
        copyTextButton.setBorder(null);
        copyTextButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(copyTextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 90, 77));

        pasteTextButton.setBackground(new java.awt.Color(0,0,0,0));
        pasteTextButton.setForeground(new java.awt.Color(255, 255, 255));
        pasteTextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IDEImages/pasteTextImage.png"))); // NOI18N
        pasteTextButton.setText("Paste Text");
        pasteTextButton.setBorder(null);
        pasteTextButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(pasteTextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 90, 77));

        redoButton.setBackground(new java.awt.Color(0,0,0,0));
        redoButton.setForeground(new java.awt.Color(255, 255, 255));
        redoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IDEImages/redoImage.png"))); // NOI18N
        redoButton.setText("Redo");
        redoButton.setBorder(null);
        redoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(redoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 100, 77));

        undoButton.setBackground(new java.awt.Color(0,0,0,0));
        undoButton.setForeground(new java.awt.Color(255, 255, 255));
        undoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IDEImages/undoImage.png"))); // NOI18N
        undoButton.setText("Undo");
        undoButton.setBorder(null);
        undoButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(undoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 100, 77));

        compileButton.setBackground(new java.awt.Color(0,0,0,0));
        compileButton.setForeground(new java.awt.Color(255, 255, 255));
        compileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IDEImages/compileImage.png"))); // NOI18N
        compileButton.setText("Compile");
        compileButton.setBorder(null);
        compileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(compileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 110, 77));

        aboutButton.setBackground(new java.awt.Color(0,0,0,0));
        aboutButton.setForeground(new java.awt.Color(255, 255, 255));
        aboutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IDEImages/aboutUsImage.png"))); // NOI18N
        aboutButton.setText("About Us");
        aboutButton.setBorder(null);
        aboutButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aboutButton.setInheritsPopupMenu(true);
        jPanel1.add(aboutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 90, 77));

        errorLabel1.setText("ErrorLog");
        jPanel1.add(errorLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 730, 176, 63));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1423, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cleanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cleanButtonActionPerformed

    private void exportTokensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportTokensActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportTokensActionPerformed

    private void exportErrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportErrorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportErrorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aboutButton;
    private javax.swing.JButton cleanButton;
    private javax.swing.JButton compileButton;
    private javax.swing.JButton copyTextButton;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JLabel errorLabel1;
    private javax.swing.JTextArea errorLogArea;
    private javax.swing.JButton exportError;
    private javax.swing.JButton exportTokens;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton newFileButton;
    private javax.swing.JButton openFileButton;
    private javax.swing.JButton pasteTextButton;
    private javax.swing.JButton redoButton;
    private javax.swing.JButton saveFileAsButton;
    private javax.swing.JButton saveFileButton;
    private javax.swing.JTextArea textWriterArea;
    private javax.swing.JTextArea textWriterArea1;
    private javax.swing.JTextArea textWriterArea2;
    private javax.swing.JTextArea tokenLogArea;
    private javax.swing.JButton undoButton;
    // End of variables declaration//GEN-END:variables
}
